### ISSUE TITLE
chat.on('QUIQ_CHAT_VISIBILITY_DID_CHANGE') not triggering

### ISSUE THREAD

**Issue by alvarezloaiciga** [Quiq/webchat#75]
I have copied and pasted what's in the docs and that event is not triggered when I open the chat window.

```javascript
    chat.on('QUIQ_CHAT_VISIBILITY_DID_CHANGE', function (e) {
      if (e.visible) {
          console.log("Chat was just made visible by user");
      } else {
          console.log("Chat was just hidden by user");
      }
    });
```

![quiq_chat_events_not_triggering](https://user-images.githubusercontent.com/1824787/42835155-701423f2-89b5-11e8-91dd-2fbd7ea52a1c.gif)

**Comment by fredvollmer** [comment]
Thanks for reporting @alvarezloaiciga , we are investigating now and will keep you posted.

**Comment by fredvollmer** [comment]
It turns out we list the incorrect event name in our documentation--this is being corrected currently. In the meantime, please use `chatVisibilityDidChange` instead of `QUIQ_CHAT_VISIBILITY_DID_CHANGE`. The corrected code would be
```
    chat.on('chatVisibilityDidChange', function (e) {
      if (e.visible) {
          console.log("Chat was just made visible by user");
      } else {
          console.log("Chat was just hidden by user");
      }
    });
```
Apologies for the mixup...let me know if there are any other issues.

**Comment by alvarezloaiciga** [comment]
Thx, just created a PR to fix the docs: https://github.com/Quiq/webchat/pull/76

**Comment by fredvollmer** [comment]
See comment https://github.com/Quiq/webchat/pull/76#issuecomment-405750245
